name: First Demo
on: [push, workflow_dispatch]
jobs:
  needs: print-hello2
  print-hello:
    name: Print Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "Hello World"

  jobs:
    print-hello2:
      name: Print Hello World2
      runs-on: ubuntu-latest
  
      steps:
        - name: Echo message2
          run: echo "Hello World2"
