name: First Demo
on: [push, workflow_dispatch]
jobs:
  print-hello:
    needs: print-hello2
    name: Print Hello World
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "Hello World"


  print-hello2:
    
    name: Print Hello World2
    runs-on: ubuntu-latest

    steps:
      - name: Echo message2
        run: echo "Hello World2"
