name: Second Demo
# on: [workflow_dispatch]
on:
  workflow_run:
    workflows: ["First Demo"]
    types: [completed]
    
jobs:
  print-hi:
    name: Print hi World
    runs-on: ubuntu-latest

    steps:
      - name: Echo message
        run: echo "hi World"


  print-hi2:
    needs: print-hi
    name: Print hi World2
    runs-on: ubuntu-latest

    steps:
      - name: Echo message2
        run: echo "hi World2"
